//! Phase Alpha-7 — DreamCoder-style dream phase: generate a substrate
//! per theory and run cross-precision analysis. ADR 0066 Direction B.
//!
//! After Phase 0 discovery (1000 ticks on OQ#1), each named theory's
//! axioms are used to *generate* an imagined substrate that satisfies
//! them by construction. Then every theory is forward-applied on
//! every generated substrate to produce a precision matrix:
//!
//!   precision[i][j] = | predict_j(substrate_i) ∩ substrate_i |
//!                     ----------------------------------------
//!                              | predict_j(substrate_i) |
//!
//! Diagonal (i == j): expected ≈ 1.0 by construction (sanity check).
//! Off-diagonal: how well theory j generalizes to theory i's
//! exemplar. < 1.0 means theory j makes false predictions on
//! substrate i.
//!
//! Hypotheses being tested:
//! - All diagonals = 1.0 (sanity)
//! - Off-diagonals VARY across pairs (i.e., generation is
//!   discriminative — substrates aren't all the same)
//! - Some theories generalize more (high mean off-diagonal precision)
//!
//! Echo-chamber guard: cross-validation across distinct theories,
//! not just self-validation. Discriminative cross-precision means
//! the dream phase is producing real information, not tautologies.
//!
//! Captured to `logs/<date>_phase_alpha_dream_phase.log`.

use relatum_v2::{
    runtime::{
        AutonomousRuntime, Event, RuleBasedScheduler,
        SyntheticStreamEnvironment,
    },
    ESTABLISHED_MARKER, PATTERN_MARKER, R, RSet,
};
use std::collections::HashSet;

const TICKS_PHASE_0: u64 = 1000;
// Sparser config: more identifiers (15 vs 8), lower density (0.05 vs
// 0.30). Aim: keep the saturated substrate FAR from complete so
// non-shared axioms (e.g., t_1's symmetry) make false predictions
// on substrates generated by theories that lack them. With
// num_ids=15, the data-data ordered-pair space is 15*14=210, a much
// larger denominator than the 8*7=56 of the original config —
// saturation under transitivity is unlikely to fill it.
const NUM_GEN_IDS: usize = 15;
const SEED_DENSITY: f64 = 0.05;
const RNG_SEED_BASE: u64 = 0xC0FFEE_DEADBEEF;

fn build_long_stream() -> Vec<(u64, Event)> {
    // OQ#1 4-regime substrate (same as prior Alpha experiments).
    let mut schedule = Vec::new();
    let regime_a_phases: [&[&str]; 5] = [
        &["a1", "a2", "a3", "a4"],
        &["a5", "a6", "a7", "a8"],
        &["a9", "a10", "a11", "a12"],
        &["a13", "a14", "a15", "a16"],
        &["a17", "a18", "a19", "a20"],
    ];
    for (i, ns) in regime_a_phases.iter().enumerate() {
        let off = 1 + (i as u64) * 100;
        for k in 0..4 {
            schedule.push((off + k as u64, Event::AddEdge(R::new(ns[k], ns[k]))));
        }
        schedule.push((off + 7, Event::AddEdge(R::new(ns[0], ns[1]))));
        schedule.push((off + 11, Event::AddEdge(R::new(ns[0], ns[2]))));
        schedule.push((off + 15, Event::AddEdge(R::new(ns[0], ns[3]))));
        schedule.push((off + 19, Event::AddEdge(R::new(ns[1], ns[3]))));
        schedule.push((off + 23, Event::AddEdge(R::new(ns[2], ns[3]))));
    }
    let regime_b_phases: [(&[&str], &[&str]); 5] = [
        (&["bL1", "bL2"], &["bR1", "bR2", "bR3"]),
        (&["bL3", "bL4"], &["bR4", "bR5", "bR6"]),
        (&["bL5", "bL6"], &["bR7", "bR8", "bR9"]),
        (&["bL7", "bL8"], &["bR10", "bR11", "bR12"]),
        (&["bL9", "bL10"], &["bR13", "bR14", "bR15"]),
    ];
    for (i, (lefts, rights)) in regime_b_phases.iter().enumerate() {
        let off = 501 + (i as u64) * 100;
        let mut t = 0u64;
        for l in lefts.iter() {
            for r in rights.iter() {
                schedule.push((off + t, Event::AddEdge(R::new(*l, *r))));
                t += 2;
            }
        }
    }
    let regime_c_phases: [&[&[&str]]; 5] = [
        &[&["c_a1", "c_a2"], &["c_b1", "c_b2", "c_b3"]],
        &[&["c_a3", "c_a4"], &["c_b4", "c_b5", "c_b6"]],
        &[&["c_a5", "c_a6"], &["c_b7", "c_b8", "c_b9"]],
        &[&["c_a7", "c_a8"], &["c_b10", "c_b11", "c_b12"]],
        &[&["c_a9", "c_a10"], &["c_b13", "c_b14", "c_b15"]],
    ];
    for (i, classes) in regime_c_phases.iter().enumerate() {
        let off = 1001 + (i as u64) * 100;
        let mut t = 0u64;
        for cls in classes.iter() {
            for x in cls.iter() {
                for y in cls.iter() {
                    schedule.push((off + t, Event::AddEdge(R::new(*x, *y))));
                    t += 1;
                }
            }
        }
    }
    let regime_d_phases: [&[&str]; 5] = [
        &["d1", "d2", "d3", "d4"],
        &["d5", "d6", "d7", "d8"],
        &["d9", "d10", "d11", "d12"],
        &["d13", "d14", "d15", "d16"],
        &["d17", "d18", "d19", "d20"],
    ];
    for (i, ns) in regime_d_phases.iter().enumerate() {
        let off = 1501 + (i as u64) * 100;
        for k in 0..4 {
            schedule.push((off + k as u64, Event::AddEdge(R::new(ns[k], ns[k]))));
        }
        schedule.push((off + 5, Event::AddEdge(R::new(PATTERN_MARKER, ns[0]))));
        schedule.push((off + 6, Event::AddEdge(R::new(ns[0], ESTABLISHED_MARKER))));
        schedule.push((off + 7, Event::AddEdge(R::new(ns[0], ns[1]))));
        schedule.push((off + 11, Event::AddEdge(R::new(ns[0], ns[2]))));
        schedule.push((off + 15, Event::AddEdge(R::new(ns[0], ns[3]))));
        schedule.push((off + 19, Event::AddEdge(R::new(ns[1], ns[3]))));
        schedule.push((off + 23, Event::AddEdge(R::new(ns[2], ns[3]))));
    }
    schedule
}

/// Forward-apply every template axiom of `theory_id` on `substrate`,
/// returning the union of predicted edges.
fn predict_all_axioms(substrate: &RSet, axiom_ids: &[String]) -> HashSet<R> {
    let mut total: HashSet<R> = HashSet::new();
    for ax in axiom_ids {
        let p = substrate.forward_apply_axiom(ax);
        total.extend(p);
    }
    total
}

/// Precision = |predicted ∩ actual| / |predicted|. Returns None if
/// no edges predicted (avoid 0/0).
fn precision(predicted: &HashSet<R>, actual: &HashSet<R>) -> Option<f64> {
    if predicted.is_empty() {
        return None;
    }
    let inter = predicted.iter().filter(|r| actual.contains(*r)).count();
    Some(inter as f64 / predicted.len() as f64)
}

fn main() {
    println!(
        "=== ADR 0066 Phase Alpha-7 — DreamCoder-style cross-precision matrix ({} ticks Phase 0) ===",
        TICKS_PHASE_0,
    );
    println!(
        "NUM_GEN_IDS={}, SEED_DENSITY={}, RNG_SEED_BASE=0x{:X}",
        NUM_GEN_IDS, SEED_DENSITY, RNG_SEED_BASE,
    );

    // ── Phase 0: discover theories on primary stream ─────────
    let (theories, axioms_by_theory, primary_rset) = {
        let mut rt = AutonomousRuntime::new(RSet::new());
        rt.environment = Box::new(SyntheticStreamEnvironment::new(build_long_stream()));
        rt.scheduler = Box::new(RuleBasedScheduler::default());
        rt.run_bounded(TICKS_PHASE_0);

        let theories: Vec<String> =
            rt.rset.theories().into_iter().map(str::to_owned).collect();
        let axioms_by_theory: Vec<Vec<String>> = theories
            .iter()
            .map(|t| {
                rt.rset
                    .theory_axioms(t)
                    .into_iter()
                    .map(str::to_owned)
                    .collect()
            })
            .collect();
        // Take the rset out (clone, since we need theories' definitions).
        let primary_rset = rt.rset.clone();
        (theories, axioms_by_theory, primary_rset)
        // rt dropped here
    };

    println!();
    println!(
        "Phase 0 complete. {} theories discovered: {:?}",
        theories.len(),
        theories
    );
    for (t, axs) in theories.iter().zip(&axioms_by_theory) {
        println!("  {}: {} axioms ({:?})", t, axs.len(), axs);
    }

    // ── Dream phase: generate substrate per theory ────────────
    println!();
    println!("=== Dream phase: generate one substrate per theory ===");
    // Collect all axiom ids across all theories so we can register
    // them in every substrate (forward_apply needs the axiom's
    // intension wired into the rset to look up its template).
    let mut all_axiom_ids: HashSet<String> = HashSet::new();
    for axs in &axioms_by_theory {
        for ax in axs {
            all_axiom_ids.insert(ax.clone());
        }
    }
    let mut substrates: Vec<RSet> = Vec::with_capacity(theories.len());
    for (i, t) in theories.iter().enumerate() {
        let seed = RNG_SEED_BASE.wrapping_add(i as u64 * 0x9E3779B97F4A7C15);
        let mut gen = primary_rset
            .generate_substrate_from_theory(t, NUM_GEN_IDS, SEED_DENSITY, seed)
            .expect("generate_substrate_from_theory");
        // Register every theory's axiom intension in the substrate so
        // forward_apply works for ANY theory's axioms — this is what
        // makes the cross-precision matrix meaningful (without it,
        // theory_j's unique axioms would silently return empty
        // predictions on substrate_i).
        for ax in &all_axiom_ids {
            gen.register_axiom_with_intension(ax);
        }
        println!(
            "  {} → substrate with {} edges, {} identifiers (seed=0x{:X})",
            t,
            gen.len(),
            gen.identifiers().len(),
            seed,
        );
        substrates.push(gen);
    }

    // ── Cross-precision matrix ────────────────────────────────
    // matrix[i][j] = precision of theory_j's axioms predicting
    // edges in substrate_i.
    println!();
    println!("=== Cross-precision matrix ===");
    println!("rows: substrate (theory_i); cols: forward-applying theory_j");
    print!("{:>10}", "");
    for t in &theories {
        print!("{:>10}", t);
    }
    println!();

    let mut matrix: Vec<Vec<Option<f64>>> = Vec::with_capacity(theories.len());
    let mut sizes_matrix: Vec<Vec<(usize, usize)>> = Vec::with_capacity(theories.len());
    for (i, sub_i) in substrates.iter().enumerate() {
        let actual_i: HashSet<R> = sub_i.iter().cloned().collect();
        let mut row: Vec<Option<f64>> = Vec::with_capacity(theories.len());
        let mut sz_row: Vec<(usize, usize)> = Vec::with_capacity(theories.len());
        print!("{:>10}", theories[i]);
        for j in 0..theories.len() {
            let predicted_j = predict_all_axioms(sub_i, &axioms_by_theory[j]);
            let in_actual =
                predicted_j.iter().filter(|r| actual_i.contains(*r)).count();
            let total = predicted_j.len();
            let p = precision(&predicted_j, &actual_i);
            row.push(p);
            sz_row.push((in_actual, total));
            match p {
                Some(v) => print!("{:>10.4}", v),
                None => print!("{:>10}", "—"),
            }
        }
        println!();
        matrix.push(row);
        sizes_matrix.push(sz_row);
    }

    println!();
    println!("=== Prediction sizes (in_actual / total_predicted) ===");
    print!("{:>10}", "");
    for t in &theories {
        print!("{:>14}", t);
    }
    println!();
    for (i, t) in theories.iter().enumerate() {
        print!("{:>10}", t);
        for (in_actual, total) in &sizes_matrix[i] {
            print!("{:>14}", format!("{}/{}", in_actual, total));
        }
        println!();
    }

    // ── Diagnostics ──────────────────────────────────────────
    println!();
    println!("=== Diagnostics ===");
    // Diagonal sanity check.
    let mut diag_ok = true;
    for (i, t) in theories.iter().enumerate() {
        match matrix[i][i] {
            Some(v) if (v - 1.0).abs() < 1e-9 => {}
            Some(v) => {
                println!(
                    "  ⚠ DIAGONAL VIOLATION: theory {} on its own substrate has precision {:.4} (expected 1.0)",
                    t, v,
                );
                diag_ok = false;
            }
            None => {
                println!(
                    "  ⚠ NO PREDICTIONS: theory {} on its own substrate emitted no predictions",
                    t,
                );
            }
        }
    }
    if diag_ok {
        println!("  ✓ Sanity: all diagonals = 1.0 (theories satisfy themselves on their own substrate)");
    }

    // Off-diagonal variance.
    let mut off_diag: Vec<f64> = Vec::new();
    for i in 0..theories.len() {
        for j in 0..theories.len() {
            if i == j {
                continue;
            }
            if let Some(v) = matrix[i][j] {
                off_diag.push(v);
            }
        }
    }
    if !off_diag.is_empty() {
        let mean = off_diag.iter().sum::<f64>() / off_diag.len() as f64;
        let var = off_diag.iter().map(|v| (v - mean).powi(2)).sum::<f64>()
            / off_diag.len() as f64;
        let min = off_diag.iter().cloned().fold(f64::INFINITY, f64::min);
        let max = off_diag.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
        println!(
            "  off-diagonal: mean={:.4} var={:.4} min={:.4} max={:.4} (n={})",
            mean,
            var,
            min,
            max,
            off_diag.len(),
        );
    }

    // Per-theory generality: column means (how well theory j
    // generalizes across all substrates).
    println!();
    println!("=== Per-theory generality (column means, excluding diagonal) ===");
    println!("{:>10} {:>15} {:>15}", "theory", "mean_precision", "min_precision");
    for j in 0..theories.len() {
        let mut sum = 0.0;
        let mut count = 0;
        let mut min_p = f64::INFINITY;
        for i in 0..theories.len() {
            if i == j {
                continue;
            }
            if let Some(v) = matrix[i][j] {
                sum += v;
                count += 1;
                if v < min_p {
                    min_p = v;
                }
            }
        }
        if count == 0 {
            println!("{:>10} {:>15} {:>15}", theories[j], "—", "—");
        } else {
            println!(
                "{:>10} {:>15.4} {:>15.4}",
                theories[j],
                sum / count as f64,
                if min_p == f64::INFINITY { 0.0 } else { min_p },
            );
        }
    }

    // Verdict
    println!();
    println!("=== Verdict ===");
    let var = if off_diag.len() >= 2 {
        let mean = off_diag.iter().sum::<f64>() / off_diag.len() as f64;
        off_diag.iter().map(|v| (v - mean).powi(2)).sum::<f64>()
            / off_diag.len() as f64
    } else {
        0.0
    };
    if !diag_ok {
        println!(
            "  → BUG — diagonal violation. generate_substrate_from_theory should produce substrates where the source theory's axioms hold at rate 1.0.",
        );
    } else if var > 0.01 {
        println!("  → POSITIVE — diagonals = 1.0; off-diagonals vary (var={:.4} ≥ 0.01)", var);
        println!("    Cross-precision is discriminative. Dream phase produces signal.");
    } else if var > 0.0 {
        println!("  → WEAK — diagonals = 1.0 but off-diagonals nearly identical (var={:.4})", var);
        println!("    All theories generalize equally across substrates. Substrate diversity may be low.");
    } else {
        println!("  → INCONCLUSIVE — only one theory or no off-diagonal data.");
    }

    println!();
    println!("--- end ---");
}
